#ifndef ERROR_MESS_H
# define ERROR_MESS_H

# define ERROR_AMOUNT_ARGS "Error: amount args in input\n"
# define ERROR_FILE_EXTENSION "Error: file extension '.cub'\n"
# define ERROR_OPEN_FILE "Error: open file\n"
# define ERROR_MLX_INIT "Error: mlx init\n"
# define ERROR_MLX_NEW_WINDOW "Error: mlx new window\n"
# define ERROR_MLX_NEW_IMAGE "Error: mlx new image\n"
# define ERROR_MALLOC "Error: malloc\n"
# define ERROR_GNL "Error: get_next_line\n"
# define ERROR_MALLOC_TOKEN "Error: malloc token\n"
# define ERROR_FILE_EMPTY "Error: file map is empty\n"
# define ERROR_FT_STRTRIM "Error: ft_strtrim\n"
# define ERROR_AMOUNT_TEXTURE "Error: amount texture\n"
# define ERROR_MIN_MAP "Error: few rows in map\n"
# define ERROR_TEXTURE_BEFORE_MAP "Error: texture after map\n"
# define ERROR_MAP_IS_SINGLE "Error: map is not single\n"
# define ERROR_INVALID_TEXTURE "Error: invalid texture\n"
# define ERROR_SEPARATOR_TEXTURE "Error: no separator\n"
# define ERROR_DUPLICATE_TEXTURE "Error: duplicate texture\n"
# define ERROR_LEN_PATH_TEXTURE "Error: len path texture\n"
# define ERROR_EXTENSION_TEXTURE "Error: extension texture\n"
# define ERROR_OPEN_TEXTURE "Error: open texture\n"
# define ERROR_MLX_GET_DATA_ADDR "Error: mlx_get_data_addr\n"
# define ERROR_NO_MAP "Error: no map in file\n"
# define ERROR_FORMAT_RGB "Error: format rgb\n"
# define ERROR_MAX_RGB "Error: value more max rgb\n"
# define ERROR_COUNT_ROWS_MAP "Error: count rows map\n"
# define ERROR_INVALID_CHR_MAP "Error: invalid char in map\n"
# define ERROR_MANY_HEROES "Error: many herous on map\n"
# define ERROR_NO_HERO "Error: no hero in map\n"
# define ERROR_BORDERS_MAP "Error: borders in map\n"

#endif